name: Python Black

on: [push, pull_request]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Setup checkout
        uses: actions/checkout@v4
      - name: Lint with Black
        run: |
          pip install black
          black --diff --check src/motile_toolbox tests
