name: Python mypy

on: [push, pull_request]

jobs:
  static-analysis:
    name: Python mypy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Setup checkout
        uses: actions/checkout@v4
      - name: Install conda dependencies
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          environment-file: conda_config.yml
          channel-priority: true
      - name: mypy
        shell: bash -el {0}  # this is necessary to activate the conda env
        run: |
          pip install ".[dev]"
          pip install --upgrade mypy
          mypy src/motile_toolbox
