name: Python mypy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static-analysis:
    name: Python mypy
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: uv sync
      - name: mypy
        run: uv run mypy src/motile_toolbox
